name: Checkout Example
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  checkout-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify repository contents
        run: |
          echo "Listing all files recursively:"
          ls -alhR
