name: Build Example

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dependencies-example:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 

      
      - name: Install dependencies
        run: npm install

      - name: build the code 
        run: npm run build

      - name: Test the code
        run: |
          echo "Running unit tests..."
          npm test -- --json --outputFile=test-results.json
          
      - name: Test rapport
        uses: dorny/test-reporter@v2
        if: always()
        with: 
          name: JUnit Tests
          path: reports/jest-results.xml
          reporter: jest-junit

      
      - name: Verify files and folders
        run: |
          echo "Listing all files recursively:"
          ls -alhR
