name: Build Example

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the code
        run: npm run build

      # 🔹 Unit tests uitvoeren en JUnit-rapport genereren
      - name: Test the code
        run: |
          echo "Running unit tests..."
          npx jest --ci --coverage --reporters=default --reporters=jest-junit --outputDirectory=reports --outputName=jest-results.xml
        env:
          CI: true

      # 🔹 Test rapport uploaden naar GitHub Actions
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: JUnit Tests
          path: reports/jest-results.xml
          reporter: jest-junit

      - name: Verify files and folders
        run: |
          echo "Listing all files recursively:"
          ls -alhR

      - name: Code Coverage Report
        uses: mridang/action-test-reporter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ./coverage/clover.xml # Path to your clover, cobertura, jacoco, or lcov file
          working-directory: ./
            # 🔹 Log in op Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🔹 Docker image bouwen
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-management-api:latest .

      # 🔹 Docker image pushen naar Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-management-api:latest


